obj-$(CONFIG_MTD_NAND_SW_ECC_IWAVE) += iwave_nand.o
obj-$(CONFIG_MTD_NAND_HW_ECC_IWAVE) += iwave_nand.o
obj-$(CONFIG_MTD_NAND_RAW_IWAVE) += iwave_nand.o
iwave_nand-objs += iwave-nfc.o
iwave_nand-objs += iwave-lib.o

